steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west9-docker.pkg.dev/bsjxygz-gcp-octo-lille/octoptimist-repo/octoptimist-service:latest', '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west9-docker.pkg.dev/bsjxygz-gcp-octo-lille/octoptimist-repo/octoptimist-service:latest']
  
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

images:
  - 'europe-west9-docker.pkg.dev/bsjxygz-gcp-octo-lille/octoptimist-repo/octoptimist-service:latest'
