project_id           = "bsjxygz-gcp-octo-lille"
region               = "europe-west9"
service_name         = "octoptimist-service"
artifact_repo_name   = "octoptimist-repo"
tag                  = "latest"
github_owner         = "Sted-octo"
github_repo_name     = "MaSynthese"